name: Ct.js Nightly
on:
  push:
    branches:
    - develop
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: Install intermediate dependencies
      run: npm install
    - name: Initialize the development environment
      run: gulp -f devSetup.gulpfile.mjs
    - name: Build and publish the app
      run: gulp deploy --nightly --buildNum=$GITHUB_SHA
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
