name: Ct.js Release
on:
  push:
    tags:
    - 'v*'
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: Install intermediate dependencies
      run: npm install
    - name: Initialize the development environment
      run: gulp -f devSetup.gulpfile.js
    - name: Build and publish the app
      run: gulp deploy --buildNum=$GITHUB_SHA
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
